name: 'hollowknight_proyect'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
clean-targets:
  - "target"
  - "dbt_packages"

models:

  +transient: false
  hollowknight_proyect:
    staging:
      +materialized: view
      +database: "{{ env_var('DBT_ENVIRONMENT') }}_SILVER"
      +schema: 'hk_dcl_dbt'
    mart: 
      +materialized: table
      +database: "{{ env_var('DBT_ENVIRONMENT') }}_GOLD"
      core:
        +schema: core

seeds:
  +schema: seed_data
  +database: "{{ env_var('DBT_ENVIRONMENT') }}_BRONZE"

snapshots:
  +transient: false
  +target_database: "{{ env_var('DBT_ENVIRONMENT') }}_SILVER"
  +target_schema: snapshots

flags:
  require_generic_test_arguments_property: true