name: 'hollowknight_proyect'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]   

target-path: "target"  
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  hk_key: "{{ env_var('DCL_HK_DEV', '_fail') }}"
  hk_key_prod: "{{ env_var('DCL_HK_PROD', 'hk_prod_default') }}"

models:
  +transient: false
  curso:
    # Applies to all files under models/example/

    staging:
      +materialized: view
      +database: "{{ env_var('DBT_ENVIRONMENTS') }}_SILVER"

      
    marts:
      +materialized: table
      +database: "{{ env_var('DBT_ENVIRONMENTS') }}_GOLD"


